# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_dmvn <- function(x, Sigma) {
    .Call('_gpbart2_log_dmvn', PACKAGE = 'gpbart2', x, Sigma)
}

bspline <- function(x, x_obs) {
    .Call('_gpbart2_bspline', PACKAGE = 'gpbart2', x, x_obs)
}

sbart <- function(x_train, y_train, x_test, B_train, B_test, D, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels, intercept_model, stump, a) {
    .Call('_gpbart2_sbart', PACKAGE = 'gpbart2', x_train, y_train, x_test, B_train, B_test, D, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels, intercept_model, stump, a)
}

mat_init <- function(n) {
    .Call('_gpbart2_mat_init', PACKAGE = 'gpbart2', n)
}

vec_init <- function(n) {
    .Call('_gpbart2_vec_init', PACKAGE = 'gpbart2', n)
}

std_inv <- function(A, diag) {
    .Call('_gpbart2_std_inv', PACKAGE = 'gpbart2', A, diag)
}

std_pinv <- function(A, diag) {
    .Call('_gpbart2_std_pinv', PACKAGE = 'gpbart2', A, diag)
}

faster_simple_std_inv <- function(A, diag) {
    .Call('_gpbart2_faster_simple_std_inv', PACKAGE = 'gpbart2', A, diag)
}

faster_std_inv <- function(A, diag) {
    .Call('_gpbart2_faster_std_inv', PACKAGE = 'gpbart2', A, diag)
}

rMVN2 <- function(b, Q) {
    .Call('_gpbart2_rMVN2', PACKAGE = 'gpbart2', b, Q)
}

rMVNslow <- function(b, Q) {
    .Call('_gpbart2_rMVNslow', PACKAGE = 'gpbart2', b, Q)
}

matrix_mat <- function(array) {
    .Call('_gpbart2_matrix_mat', PACKAGE = 'gpbart2', array)
}

rand_unif <- function() {
    .Call('_gpbart2_rand_unif', PACKAGE = 'gpbart2')
}

inn_prod_one <- function(beta_vec) {
    .Call('_gpbart2_inn_prod_one', PACKAGE = 'gpbart2', beta_vec)
}

inn_prod_two <- function(beta_vec) {
    .Call('_gpbart2_inn_prod_two', PACKAGE = 'gpbart2', beta_vec)
}

inn_prod_three <- function(beta_vec) {
    .Call('_gpbart2_inn_prod_three', PACKAGE = 'gpbart2', beta_vec)
}

array_check <- function(arr_) {
    invisible(.Call('_gpbart2_array_check', PACKAGE = 'gpbart2', arr_))
}

