# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gamma_pdf <- function(x, a, b) {
    .Call('_bart2_gamma_pdf', PACKAGE = 'bart2', x, a, b)
}

r_gamma_pdf <- function(x, a, b) {
    .Call('_bart2_r_gamma_pdf', PACKAGE = 'bart2', x, a, b)
}

print_mat_subset <- function(X) {
    invisible(.Call('_bart2_print_mat_subset', PACKAGE = 'bart2', X))
}

log_dmvn <- function(x, Sigma) {
    .Call('_bart2_log_dmvn', PACKAGE = 'bart2', x, Sigma)
}

cppbart <- function(x_train, y_train, x_test, n_tree, node_min_size, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau, stump) {
    .Call('_bart2_cppbart', PACKAGE = 'bart2', x_train, y_train, x_test, n_tree, node_min_size, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau, stump)
}

mat_init <- function(n) {
    .Call('_bart2_mat_init', PACKAGE = 'bart2', n)
}

vec_init <- function(n) {
    .Call('_bart2_vec_init', PACKAGE = 'bart2', n)
}

std_inv <- function(A, diag) {
    .Call('_bart2_std_inv', PACKAGE = 'bart2', A, diag)
}

std_pinv <- function(A, diag) {
    .Call('_bart2_std_pinv', PACKAGE = 'bart2', A, diag)
}

faster_simple_std_inv <- function(A, diag) {
    .Call('_bart2_faster_simple_std_inv', PACKAGE = 'bart2', A, diag)
}

log_test <- function(a) {
    .Call('_bart2_log_test', PACKAGE = 'bart2', a)
}

faster_std_inv <- function(A, diag) {
    .Call('_bart2_faster_std_inv', PACKAGE = 'bart2', A, diag)
}

rMVN2 <- function(b, Q) {
    .Call('_bart2_rMVN2', PACKAGE = 'bart2', b, Q)
}

rMVNslow <- function(b, Q) {
    .Call('_bart2_rMVNslow', PACKAGE = 'bart2', b, Q)
}

matrix_mat <- function(array) {
    .Call('_bart2_matrix_mat', PACKAGE = 'bart2', array)
}

rand_unif <- function() {
    .Call('_bart2_rand_unif', PACKAGE = 'bart2')
}

inn_prod_one <- function(beta_vec) {
    .Call('_bart2_inn_prod_one', PACKAGE = 'bart2', beta_vec)
}

inn_prod_two <- function(beta_vec) {
    .Call('_bart2_inn_prod_two', PACKAGE = 'bart2', beta_vec)
}

inn_prod_three <- function(beta_vec) {
    .Call('_bart2_inn_prod_three', PACKAGE = 'bart2', beta_vec)
}

array_check <- function(arr_) {
    invisible(.Call('_bart2_array_check', PACKAGE = 'bart2', arr_))
}

